# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe" 
CFLAGS="${COMMON_FLAGS}" 
CXXFLAGS="${COMMON_FLAGS}" 
FCFLAGS="${COMMON_FLAGS}" 
FFLAGS="${COMMON_FLAGS}" 
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"

# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo" 
DISTDIR="/var/cache/distfiles" 
PKGDIR="/var/cache/binpkgs" 

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C

# FIXME: adjust as needed (see: https://wiki.gentoo.org/wiki//etc/portage/make.conf#VIDEO_CARDS)
VIDEO_CARDS="fbdev" 
# FIXME: adjust as needed (see: https://wiki.gentoo.org/wiki//etc/portage/make.conf#INPUT_DEVICES)
INPUT_DEVICES="libinput"

ACCEPT_LICENSE="*" 

# FIXME: adjust as needed (see: https://wiki.gentoo.org/wiki/GRUB#Prerequisites)
GRUB_PLATFORMS="efi-64" 

# FIXME: adjust as needed (see: https://wiki.gentoo.org/wiki/MAKEOPTS)
MAKEOPTS="-j10" 

# We split USE flags out into a separate file to make this file more managable
source /etc/portage/make.use

# FIXME: adjust as needed (see: https://wiki.gentoo.org/wiki/QEMU#USE_EXPAND)
# uncomment one of these that matches the host CPU:
#QEMU_SOFTMMU_TARGETS="x86_64 i386" 
#QEMU_SOFTMMU_TARGETS="arm aarch64" 
# uncomment one of these that matches the host CPU:
#QEMU_USER_TARGETS="x86_64" 
#QEMU_USER_TARGETS="aarch64" 

# FIXME: adjust as needed (see: https://wiki.gentoo.org/wiki/GENTOO_MIRRORS)
#GENTOO_MIRRORS="https://gentoo.osuosl.org/"
